### ISSUE TITLE
JNI

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#10]
- [x] Segfaults in C JNI abfangen
- [x] Fehler Compilezeit Java ArrayArgs verschiedene Typen
- [x] Executor-Klasse direktes ausführen von Kernel
- [x] Zeitmessungen JNI implementieren
- [x] Bug ExampleBlockReduce.java

**Comment by zeratax** [comment]
Ich merge bald meine Branche und da übergebe ich device beim launch.
Also so launch(args, device)
Und device ist optional.

ProgramArg -> KernelArg

**Comment by zeratax** [comment]
du benutzt dieses issue aber auch für alles lmao @LukasSiefke

**Comment by LukasSiefke** [comment]
Ja, ich sollte vielleicht mal mehr kleinere Issues machen...
