### ISSUE TITLE
Nehme die printfs bei der Erstellung der Exceptions raus

### ISSUE THREAD

**Issue by visualJames** [ZerataX/cudacompiler#107]
neben bei wofür sind eig diese printf statements?
https://github.com/ZerataX/yacx/blob/master/include/yacx/Exception.hpp#L97

Diese Printfs sollen rausgenommen werden

**Comment by zeratax** [comment]
wie gesagt, vielleicht macht es Sinn statt dessen dort den logger zu benutzen?

**Comment by visualJames** [comment]
Ok, dann gebe ich die Sachen mit den Logger aus

**Comment by visualJames** [comment]
fixed with #109
