### ISSUE TITLE
ProgrammArg

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#11]
Gibt es auch Args, die nicht geuploadet werden müssen? Attribut _upload notwendig?

**Comment by zeratax** [comment]
Denke du hast es selber schon rausgefunden?
aber da es noch nicht dokumentiert ist erkläre ich es hier nochmal:
upload: es wird auf dem device speicher alloziert (nicht nötig für grundlegende typen wie int, short, char etc)
copy: die variable wird kopiert (für output arrays ist das oft nicht nötig)
download: nach ausführen wird die variable vom device zum host kopiert

wenn man einfach eine konstante braucht kann man das also so machen:
```c++
std::vector<ProgramArg> args;
size_t n = 5;
args.emplace_back(ProgramArg{&n})
```
was das selbe ist wie:
```c++
std::vector<ProgramArg> args;
size_t n = 5;
args.emplace_back(ProgramArg{&n, 0, download:false, upload:false, copy:false})
```
