### ISSUE TITLE
Exceptions in Destructors lead to crashes

### ISSUE THREAD

**Issue by hadis1000** [ZerataX/cudacompiler#12]
See usage of NVRTC_SAFE_CALL

Exceptions should never leave the destructor of an object.

**Comment by zeratax** [comment]
ja schon klar, aber weiß nicht wie man ansonsten damit ungehen soll? also garnicht erst diese funktionen da benutzen oder einfach nur loggen? weil würde ja schon gerne wissen ob da was schief läuft

**Comment by zeratax** [comment]
more or less fixed with https://github.com/ZerataX/cudacompiler/commit/b5066686b7e0478b5804a91480999ca685b398a3
currently it just doesn't check for an error, but probably later should again, just not with an exception
