### ISSUE TITLE
Execute Cuda Host functions

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#125]

**Comment by LukasSiefke** [comment]
Keine Lust darauf. Ist irgendwie nicht so einfach. Ich nutze für die Umwandlung von halfs zu floats dann einfach normalen CUDA-Kernel...

**Comment by zeratax** [comment]
was sollte das den überhaupt sein?

**Comment by LukasSiefke** [comment]
Man kann nicht nur auf einem CUDA-Device CUDA-Kernel ausführen sondern auch mit der CPU CUDA-Host-Functions. Die hätten Verwendung gefunden beim Umwandeln von floats to halfs. Jetzt wird float* zu half* konvertiert durch Ausführung eines CUDA-Kernels.
