### ISSUE TITLE
Deviceselection for kernelexecution for conversion from float to half

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#127]
For conversion from floats to halfs we need to start a CUDA-kernel, that executes this conversion.
For this we need a Device capable of CUDA version 6 or higher. Currently we just select any device which could be a problem when multiple devices are available.

When #57 is done and we can list Devices, we could also select a Device with CUDA version 6 or higher before executing the Kernel

**Comment by zeratax** [comment]
I really like how this achieves similar functionality https://github.com/mgopshtein/cudacpp/blob/master/examples/invoke-rtc.cpp#L15

**Comment by ZerataX** [comment]
is this also possible with #141?
