### ISSUE TITLE
Add loglevel to log output of our logger

### ISSUE THREAD

**Issue by hadis1000** [ZerataX/cudacompiler#13]

**Comment by LukasSiefke** [comment]
Und vieleicht auch noch aktuelle Zeit?

**Comment by zeratax** [comment]
hier wäre es halt jetzt super ENUMS zu strings zu machen. oder vielleicht einfach manuel ne map dafür oder sowas

**Comment by hadis1000** [comment]
Ich setze mich mal dran.

**Comment by hadis1000** [comment]
Kannst du uns Rechte geben? @ZerataX
