### ISSUE TITLE
Shared Memory benutzen

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#130]
Beim Kernellaunch muss man ja noch die Anzahl der zu verwendenden Bytes an shared memory spezifizieren. Momentan ist das konstant 0. Dann kann man also kein shared memory in seinen Kernels benutzen

**Comment by zeratax** [comment]
also noch ne flag bei kernelarg dann oder brauchen wir doch noch so ne globalarg?

**Comment by LukasSiefke** [comment]
Ich glaube wir brauchen ein int-Parameter bei der launch-Methode

**Comment by zeratax** [comment]
achso und dann hat der Kernel das zur Verfügung? okay ja macht Sinn

**Comment by LukasSiefke** [comment]
Das machen wir dann ja irgendwie direkt im generierten KernelCode
