### ISSUE TITLE
make

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#15]
Einfache Ausführung mit einem Befehl? (make und make run)
Bisher sind da in jedem Unterordner ein Makefile und es ist nicht klar, welchen man ausführen soll und was letztendlich die Ausführungsdatei ist
(von Andre)

**Comment by zeratax** [comment]
die makefiles in test und examples builden nur die objects für die cpp dateien da drinne.
der makefile im root ordner linked das dann alles.
wenn man nur make eingibt wird einfach das oberste ausgeführt also wird _example_program_ erstellt.
alle programme werden nach `./bin/runner` ausgeben.
tests haben ihren eigenen runner unter `./bin/tests`

Zur zeit kann man:
  - make example_template
  - make example_saxpy
  - make example_program
  - make check (erstellt und führt tests aus)
  - make clean (löscht build und bin)
  - make format (formatiert alles nach .clang-format)
  - make lint (linted mit cpplint, aber clang-tidy wäre cooler)
