### ISSUE TITLE
Consistent naming scheme / Design

### ISSUE THREAD

**Issue by zeratax** [ZerataX/cudacompiler#2]
- [x] Classes
  - [x] private attributes `_var` vs `var_m`
- [x] Testfiles
- [x] ProgramArg vs KernelArg
- [x] Kernel vs Program
- [x] instantiate

```c++
.instantiate(type_of(data), 5)
.instantiate<float, std::integral_constant<int, 5>>()
```

**Comment by hadis1000** [comment]
Ich bin fuer m_var.
So kann man in der ganzen datei nach m_ suchen um alle member variablen zu finden.

**Comment by hadis1000** [comment]
Nach der umbennung von Kernel und Program sollten die args jetzt KernelArgs heissen.

**Comment by hadis1000** [comment]
Meinungen?

**Comment by zeratax** [comment]
+1 m_var
+1 KernelArg

**Comment by zeratax** [comment]
`.instantiate(type_of(data), 5) +1`
Ich glaube das kann man dann einfach für `is_arithmetic` und strings instantieren und dann gut linken. 

**Edit:** Okay eig gehen variadic funktionen wohl nie als library nehme ich an. Trotzdem finde ich das Format am schönsten. Muss man halt dann für einen string initialisieren, e.g.
`.initialize("int, int 5"}`, wenn man es dann im executor verwenden will
