### ISSUE TITLE
select Device per UUID

### ISSUE THREAD

**Issue by zeratax** [ZerataX/cudacompiler#57]

**Comment by LukasSiefke** [comment]
Additionally listing all devices would also be nice.

**Comment by zeratax** [comment]
regex for UUID:
```regex
[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}
```

**Comment by LukasSiefke** [comment]
Schön, dass auf dem Agamemnon anscheinend keine `cuDeviceGetUuid`-Methode existiert, aber immerhin auf dem Palma.
Ist dann halt nicht so cool für unsere continuous integration, wenns auf dem Agamemnon nicht mehr kompilierbar ist.
