### ISSUE TITLE
compgen - autocompletion of options in the execucatble in the command line

### ISSUE THREAD

**Issue by visualJames** [ZerataX/cudacompiler#60]
Imagine you use a command like ls and you would like to list all files, including hidden files, and you don't know which option you have to use. You can simply write ''ls -" and then TAB to get autocompletion. We have a project with lot's of different options. With compgen we can possibly tell the shell which options exist and how they are described, so we are able to simply TAB and get the autocompletion like in the example of ''ls -'' above.

**Comment by LukasSiefke** [comment]
Hauptsächlich werden wir das ganze ja von Scala aus nutzen und dabei das JNI benutzen...
Oder meinst du mehr das Shell-Skript zum starten einer Java/Scala-Klasse?

**Comment by zeratax** [comment]
also https://github.com/ZerataX/cudacompiler/blob/master/cudaexecutor.sh
