### ISSUE TITLE
create uml-class-diagram

### ISSUE THREAD

**Issue by visualJames** [ZerataX/cudacompiler#61]
I've already created a class diagram of the executer, but I have to edit it. 
[ExecuterDiagrammStandalone.pdf](https://github.com/ZerataX/cudacompiler/files/3935150/ExecuterDiagrammStandalone.pdf) If you recognize things, that have to be changed, please post under this thread/issue. After finishing it, it could be a part of the documentation of our code.

**Comment by LukasSiefke** [comment]
-launch (Kernel-Klasse) liefert jetzt eine KernelTime-struct zurück, um Laufzeit angeben zu können
-Viele der Klassen erben vom JNIHandler
-Eine KernelArgs Klasse besteht jetzt prinzipiell aus einer Liste von KernelArg-Objekten

Und es gibt natürlich noch die ganzen Java-Klassen, die aber im Prinzip nur die Methoden von den C-Objekten aufrufen...

**Comment by visualJames** [comment]
Sollte JNI mit den wichtigsten Klassen im Klassendiagramm integriert werden? Die Frage ist nur in wie weit wir dann im Klassendiagramm eine Dopplung haben, weil JNI und der Executer ziemlich gleich vom Klassenaufbau ist.

**Comment by LukasSiefke** [comment]
Ja, ich glaube auch, dass ein integrieren der Java-Klassen ziemlich redundant wäre

**Comment by visualJames** [comment]
[ExecuterDiagrammStandalone.pdf](https://github.com/ZerataX/yacx/files/3936230/ExecuterDiagrammStandalone.pdf)
Hier ist jetzt das Diagramm überarbeitet. Ich habe dein ersten Punkt (KernelTime-struct in launch hinzufügen) und dein letzten Punkt mit KernelArgs umgesetzt. Desweiteren habe ich es ein wenig umstrukturiert und Aggregationen hinzugefügt, wie ich vorher mit Jona besprochen habe. Gibt es noch etwas was man schöner lösen könnte oder was man noch gut umsetzen kann, sonst schließe ich dieses Issue und pushe es dann rein. In welchen Ordner ist die Dokumentation zu finden, sodass ich es dort reinpushe?

**Comment by visualJames** [comment]
Klassendiagramm ist oben
