### ISSUE TITLE
JNI returns einfügen nach dem Werfen von Java Exceptions

### ISSUE THREAD

**Issue by LukasSiefke** [ZerataX/cudacompiler#65]
Wirft zwar momentan eine Java-Exception bei z.B. ungültigen Argumenten, der C-Code wir aber weiter ausgeführt :)

**Comment by visualJames** [comment]
Müssen dann in allen try catch Blöcken in unserem C-Host Code im catch Block ein return hinzugefügt werden?

**Comment by LukasSiefke** [comment]
Ne, das betrifft nur das JNI. Sollte relativ schnell machbar sein.
