### ISSUE TITLE
doxygen ignore Java?

### ISSUE THREAD

**Issue by zeratax** [ZerataX/cudacompiler#74]
The autolink function of doxygen always automatically links to the java classes instead of the c++ classes, e.g. https://zeratax.github.io/yacx/class_kernel_arg.html

Additionally we should consider using doxygen to generate javadoc as well if possible. see #68

**Comment by LukasSiefke** [comment]
I think javadoc is nice, but maybe doxygen can work with javadoc

**Comment by zeratax** [comment]
I am fairly sure that is possible, but I have not tested it yet
