### ISSUE TITLE
run tests on CI

### ISSUE THREAD

**Issue by zeratax** [ZerataX/cudacompiler#76]
this is like a wishlist kinda thing, but with something like this https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners

we could just use github actions to test our code on every push. sweet stuff

**Comment by LukasSiefke** [comment]
Installier mal travis auf github

**Comment by LukasSiefke** [comment]
Damit kann man auch automatisch alle Tests ausführen nach jedem Push.
Dazu müsste man folgendes machen:

```sh
sudo: required
before_install:
  - sudo apt-get install sshpass

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - echo $TEST
  - echo $HOST
  - sshpass -p $PASSWORT ssh -o StrictHostKeyChecking=no $HOST -t "./runTest"```


Mach eine Datei .travis.yml 
Und bei Travis muss du dann noch die PASSWORT und HOST Variable setzen
Dann verbindet sich das Ding mit dem agamemnon und führt da ein shell-Skript aus, welches dann die Tests ausführen kann

**Comment by zeratax** [comment]
hab das jetzt mit github actions gemacht (594cd80dfe59bc8270c210be449a85b46d9d0a0f), klappt aber nur so fast. push on master klappt toll, siehe:
https://github.com/ZerataX/yacx/commit/d63d29a67526c6e56036589af62d2e7c69d36129/checks?check_suite_id=348084741
![grafik](https://user-images.githubusercontent.com/5024958/70396565-8618f880-1a0a-11ea-8d44-421051978557.png)

aber bei pull requests auf master ist `$GITHUB_SHA` also eig der commit hash irg ein commit, dass noch garnicht existiert?
https://github.com/ZerataX/yacx/pull/77/checks?check_run_id=339150239#step:3:40

**Comment by LukasSiefke** [comment]
cool, dass das auch damit funktioniert. Ich hätte gedacht, dass das wegen dem CUDA-Zeug so nicht funktioniert...

**Comment by zeratax** [comment]
also ist auch per ssh

**Comment by zeratax** [comment]
fixed with ae2b17a8347c53763fc0e18b4a793fac12fb5f7f
