### ISSUE TITLE
logger

### ISSUE THREAD

**Issue by zeratax** [ZerataX/cudacompiler#9]
Set logging level at runtime or only at compile?

If only at compile make it easier to set with cmake/make

**Comment by hadis1000** [comment]
I'm voting for setting log levels at runtime.
Performance gains from setting the log level at compile time are negligible
and I don't see any gains other than perf.

**Comment by LukasSiefke** [comment]
Ja, ich bin auch für runtime. Die Performance vom Executor war ja sowieso nicht so super wichtig

**Comment by zeratax** [comment]
@hadis1000 machst du das auch und kann man deine branch schon mergen?

**Comment by LukasSiefke** [comment]
Von heinrich: Hab vergessen zu pushen. Kommt dann...
