### ISSUE TITLE
Compiler Warning

### ISSUE THREAD

**Issue by visualJames** [ZerataX/cudacompiler#96]
No Compiler Warning should appear

**Comment by visualJames** [comment]
Many warnings are because of JNI classes. For example there is following warning: 
YACX/yacx/src/jni/Kernel.cpp:67:1: warning: control reaches end of non-void function [-Wreturn-type]
 }

All warning in JNI are because of  warning: control reaches end of non-void function [-Wreturn-type]
This Warnings only appear on my computer with GeForce MX150. But on the agamemnon are different warnings.

**Comment by zeratax** [comment]
fixed with #98
